/**
 * Test Fixtures
 *
 * Sample data for test scenarios.
 */

/**
 * Sample research report HTML
 */
export const sampleResearchReport = `<!DOCTYPE html>
<html>
<head>
  <title>Competitor Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #333; border-bottom: 2px solid #E8FF58; }
    h2 { color: #555; margin-top: 30px; }
    .metric { background: #f5f5f5; padding: 15px; margin: 10px 0; border-radius: 8px; }
    .metric-value { font-size: 24px; font-weight: bold; color: #E8FF58; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #333; color: white; }
  </style>
</head>
<body>
  <h1>Skincare Market Competitor Analysis</h1>
  <p>Generated: ${new Date().toISOString()}</p>

  <h2>Executive Summary</h2>
  <p>This report analyzes the competitive landscape in the skincare market, focusing on key players, market positioning, and growth opportunities.</p>

  <h2>Key Metrics</h2>
  <div class="metric">
    <div class="metric-value">$15.2B</div>
    <div>Total Addressable Market</div>
  </div>
  <div class="metric">
    <div class="metric-value">8.2%</div>
    <div>Year-over-Year Growth</div>
  </div>
  <div class="metric">
    <div class="metric-value">45</div>
    <div>Active Competitors Analyzed</div>
  </div>

  <h2>Competitor Breakdown</h2>
  <table>
    <tr>
      <th>Brand</th>
      <th>Market Share</th>
      <th>Growth Rate</th>
      <th>Key Strength</th>
    </tr>
    <tr>
      <td>CeraVe</td>
      <td>12.5%</td>
      <td>+15%</td>
      <td>Dermatologist endorsement</td>
    </tr>
    <tr>
      <td>The Ordinary</td>
      <td>8.3%</td>
      <td>+22%</td>
      <td>Price transparency</td>
    </tr>
    <tr>
      <td>La Roche-Posay</td>
      <td>7.8%</td>
      <td>+8%</td>
      <td>Medical credibility</td>
    </tr>
    <tr>
      <td>Neutrogena</td>
      <td>11.2%</td>
      <td>+3%</td>
      <td>Mass market distribution</td>
    </tr>
    <tr>
      <td>Olay</td>
      <td>9.5%</td>
      <td>-2%</td>
      <td>Brand recognition</td>
    </tr>
  </table>

  <h2>Market Trends</h2>
  <ul>
    <li><strong>Clean Beauty:</strong> 68% of consumers prefer products with natural ingredients</li>
    <li><strong>Personalization:</strong> AI-driven skincare recommendations growing 35% annually</li>
    <li><strong>Sustainability:</strong> 52% willing to pay premium for eco-friendly packaging</li>
    <li><strong>K-Beauty Influence:</strong> Korean skincare trends driving 10+ step routines</li>
  </ul>

  <h2>Recommendations</h2>
  <ol>
    <li>Focus on ingredient transparency to compete with The Ordinary</li>
    <li>Partner with dermatologists for credibility boost</li>
    <li>Invest in sustainable packaging initiatives</li>
    <li>Develop AI-powered skin analysis tools</li>
  </ol>

  <h2>Appendix: Data Sources</h2>
  <ul>
    <li>Nielsen Market Research Q4 2024</li>
    <li>Reddit r/SkincareAddiction sentiment analysis (50,000 posts)</li>
    <li>TikTok hashtag analysis (#skincare, #skincareaddict)</li>
    <li>Amazon Best Sellers category tracking</li>
  </ul>

  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px;">
    <p>Report generated by Pixell AI | Confidential</p>
  </footer>
</body>
</html>`

/**
 * Sample content ideas JSON
 */
export const sampleContentIdeas = JSON.stringify({
  generatedAt: new Date().toISOString(),
  category: 'skincare',
  ideas: [
    {
      id: 1,
      title: 'Morning vs Night Skincare Routine',
      format: 'carousel',
      platform: 'instagram',
      description: 'Side-by-side comparison of AM vs PM routines',
      hashtags: ['#skincareroutine', '#morningroutine', '#nightroutine'],
      estimatedEngagement: 'high',
    },
    {
      id: 2,
      title: 'Ingredient Spotlight: Niacinamide',
      format: 'reel',
      platform: 'instagram',
      description: 'Educational content about niacinamide benefits',
      hashtags: ['#niacinamide', '#skincareingredients', '#glowyskin'],
      estimatedEngagement: 'medium',
    },
    {
      id: 3,
      title: 'Real Customer Transformations',
      format: 'ugc_compilation',
      platform: 'tiktok',
      description: 'Before/after results from real customers',
      hashtags: ['#skincaretransformation', '#beforeandafter', '#results'],
      estimatedEngagement: 'very_high',
    },
    {
      id: 4,
      title: '5 Skincare Myths Debunked',
      format: 'series',
      platform: 'tiktok',
      description: 'Quick myth-busting videos',
      hashtags: ['#skincaremyths', '#skincareabc', '#dermatologist'],
      estimatedEngagement: 'high',
    },
    {
      id: 5,
      title: 'Behind the Scenes at Our Lab',
      format: 'story_highlights',
      platform: 'instagram',
      description: 'Show product development process',
      hashtags: ['#behindthescenes', '#skincarebrand', '#productdevelopment'],
      estimatedEngagement: 'medium',
    },
    {
      id: 6,
      title: 'Seasonal Skincare Switches',
      format: 'blog_post',
      platform: 'website',
      description: 'How to adjust routine for winter',
      hashtags: ['#winterskincare', '#seasonalskincare', '#dryskin'],
      estimatedEngagement: 'medium',
    },
    {
      id: 7,
      title: 'Ask a Dermatologist Q&A',
      format: 'live',
      platform: 'instagram',
      description: 'Live session with partnered dermatologist',
      hashtags: ['#askadermatologist', '#skincarelive', '#qa'],
      estimatedEngagement: 'high',
    },
    {
      id: 8,
      title: 'Ingredient Deep Dive: Retinol',
      format: 'long_form_video',
      platform: 'youtube',
      description: 'Comprehensive guide to using retinol',
      hashtags: ['#retinol', '#antiaging', '#skincareguide'],
      estimatedEngagement: 'high',
    },
    {
      id: 9,
      title: 'Customer Routine of the Week',
      format: 'weekly_feature',
      platform: 'instagram',
      description: 'Spotlight customer routines using products',
      hashtags: ['#customerroutine', '#skincarecommunity', '#routine'],
      estimatedEngagement: 'medium',
    },
    {
      id: 10,
      title: 'Glow-Up Challenge',
      format: 'campaign',
      platform: 'tiktok',
      description: '30-day skincare challenge with prizes',
      hashtags: ['#glowupchallenge', '#skincarechallenge', '#30daychallenge'],
      estimatedEngagement: 'very_high',
    },
  ],
}, null, 2)

/**
 * Sample small report (for tier testing)
 */
export const sampleSmallReport = `<html>
<body>
  <h1>Quick Analysis</h1>
  <p>Brief overview of key findings.</p>
  <ul>
    <li>Point 1: Market is growing</li>
    <li>Point 2: Competition is increasing</li>
  </ul>
</body>
</html>`

/**
 * Sample scheduled post content
 */
export const sampleScheduledPost = {
  platform: 'reddit',
  subreddit: 'SkincareAddiction',
  title: 'My 6-Month Skincare Journey Results',
  content: `Hey everyone!

I wanted to share my results after 6 months of consistent skincare.

**Routine:**
- AM: Gentle cleanser, Vitamin C serum, moisturizer, SPF 50
- PM: Oil cleanser, water-based cleanser, retinol (3x week), moisturizer

**Results:**
- Hyperpigmentation reduced by 70%
- Texture much smoother
- Fewer breakouts

Happy to answer any questions! [Photos in comments]`,
  scheduledFor: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
}
